version: "3.5"
services:

  9fin-sentence-transformer:
    image: 9fin_projects/sentence_transformer:${TAG}
    container_name: 9fin-sentence-transformer
    command: python ./script.py
    environment:
      - DATA_LOCATION=/project/data
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
    volumes:
      - type: bind
        source: ./data
        target: /project/data

networks:
  default:
    driver: bridge
