version: '3'

tasks:
  prep_env:
    cmds:
      - poetry install
      - poetry run pre-commit install
      - poetry shell

  build_image:
    vars:
      TAG:
        sh: echo dev-$(shasum -a 256 poetry.lock Dockerfile | shasum -a 256 | cut -c1-8)
    cmds:
      - docker build --target base_image -t 9fin_projects/sentence_transformer:{{.TAG}} .

  run_script:
    vars:
      TAG:
        sh: echo dev-$(shasum -a 256 poetry.lock Dockerfile | shasum -a 256 | cut -c1-8)
    cmds:
      - TAG={{.TAG}} docker compose up -d
      - docker logs -f 9fin-sentence-transformer
      - TAG={{.TAG}} docker compose down

  stop_container:
    vars:
      TAG:
        sh: echo dev-$(shasum -a 256 poetry.lock Dockerfile | shasum -a 256 | cut -c1-8)
    cmds:
      - TAG={{.TAG}} docker compose down
